### ISSUE TITLE
Implement email validator

### ISSUE THREAD

**Issue by maany** [WLCG-Lightweight-Sites/wlcg_lightweight_site_config_validation_engine#1]
Write a basic validation rule for email validation in the file:
https://github.com/WLCG-Lightweight-Sites/wlcg_lightweight_site_config_validation_engine/blob/master/config_validation_engine/validators/validators.py

Instructions:
- Create a new function named email_domain_validator. The input params to the function include a string called domain and a list named addresses.
- Validate each email address individually. You can use the parseaddr function from email.utils. 
- Validate that domain names for all addresses in the list match.

**Comment by pumpkinman008** [comment]
@maany What checks should the email validator perform?

**Comment by maany** [comment]
@pumpkinman008 , I've updated the description. Thanks for working on this ;) Let me know if there any other questions.

**Comment by pumpkinman008** [comment]
```
def email_domain_validator(domain, addresses):
    for address in addresses:
        name, email_addr = parseaddr(address)
        email_parts = email_addr.split(u'@')
        if (domain == email_parts[1]):
            print("Valid email address: ",email_addr)
        else:
            print("Invalid email address: ",email_addr)

email_domain_validator('cern.ch',['example.example@cern.ch','example@gmail.com'])
```
Something like this?

**Comment by maany** [comment]
Looks good @pumpkinman008 . Can you integrate this in your PR?

**Comment by pumpkinman008** [comment]
@maany done
